# Generated by Django 4.2.27 on 2025-12-20 22:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('url_cctv', models.URLField(blank=True, max_length=500, null=True)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CCTV',
                'verbose_name_plural': 'CCTV',
                'db_table': 'cctv',
            },
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desa',
                'verbose_name_plural': 'Desa',
                'db_table': 'desa',
            },
        ),
        migrations.CreateModel(
            name='JenisKejahatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis_kejahatan', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Kejahatan',
                'verbose_name_plural': 'Jenis Kejahatan',
                'db_table': 'jenis_kejahatan',
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'db_table': 'kecamatan',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='PosKeamanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_keamanan', to='core.desa')),
            ],
            options={
                'verbose_name': 'Pos Keamanan',
                'verbose_name_plural': 'Pos Keamanan',
                'db_table': 'pos_keamanan',
            },
        ),
        migrations.CreateModel(
            name='NamaKejahatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_kejahatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_kejahatan', to='core.jeniskejahatan')),
            ],
            options={
                'verbose_name': 'Nama Kejahatan',
                'verbose_name_plural': 'Nama Kejahatan',
                'db_table': 'nama_kejahatan',
            },
        ),
        migrations.CreateModel(
            name='LaporanKejahatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelapor', models.CharField(max_length=200)),
                ('tanggal_kejadian', models.DateField()),
                ('waktu_kejadian', models.TimeField()),
                ('alamat', models.TextField()),
                ('deskripsi', models.TextField()),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_kejahatan', to='core.desa')),
                ('jenis_kejahatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan', to='core.jeniskejahatan')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_kejahatan', to='core.kecamatan')),
                ('nama_kejahatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan', to='core.namakejahatan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laporan_kejahatan', to='core.status')),
            ],
            options={
                'verbose_name': 'Laporan Kejahatan',
                'verbose_name_plural': 'Laporan Kejahatan',
                'db_table': 'laporan_kejahatan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KejadianLainnya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelapor', models.CharField(max_length=200)),
                ('nama_kejadian', models.CharField(max_length=200)),
                ('deskripsi_kejadian', models.TextField()),
                ('tanggal_kejadian', models.DateField()),
                ('waktu_kejadian', models.TimeField()),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kejadian_lainnya', to='core.desa')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kejadian_lainnya', to='core.kecamatan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kejadian_lainnya', to='core.status')),
            ],
            options={
                'verbose_name': 'Kejadian Lainnya',
                'verbose_name_plural': 'Kejadian Lainnya',
                'db_table': 'kejadian_lainnya',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoPosKeamanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='pos_keamanan/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos_keamanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='core.poskeamanan')),
            ],
            options={
                'verbose_name': 'Foto Pos Keamanan',
                'verbose_name_plural': 'Foto Pos Keamanan',
                'db_table': 'foto_pos_keamanan',
            },
        ),
        migrations.CreateModel(
            name='FotoLaporanKejahatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='laporan_kejahatan/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laporan_kejahatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='core.laporankejahatan')),
            ],
            options={
                'verbose_name': 'Foto Laporan Kejahatan',
                'verbose_name_plural': 'Foto Laporan Kejahatan',
                'db_table': 'foto_laporan_kejahatan',
            },
        ),
        migrations.CreateModel(
            name='FotoKejadianLainnya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='kejadian_lainnya/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kejadian_lainnya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='core.kejadianlainnya')),
            ],
            options={
                'verbose_name': 'Foto Kejadian Lainnya',
                'verbose_name_plural': 'Foto Kejadian Lainnya',
                'db_table': 'foto_kejadian_lainnya',
            },
        ),
        migrations.CreateModel(
            name='FotoCCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='cctv/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cctv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='core.cctv')),
            ],
            options={
                'verbose_name': 'Foto CCTV',
                'verbose_name_plural': 'Foto CCTV',
                'db_table': 'foto_cctv',
            },
        ),
        migrations.AddField(
            model_name='desa',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desa', to='core.kecamatan'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='desa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv', to='core.desa'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv', to='core.kecamatan'),
        ),
    ]
